services:
  distributor-bot:
    image: c4tplatform/camino-messenger-bot

    volumes:
      - ./distributor/cmb-config/:/cmb-config/

    command: |
      --config /cmb-config/messenger-config.yaml

    ports:
      - "9090:9090"

  supplier-bot:
    image: c4tplatform/camino-messenger-bot

    volumes:
      - ./supplier/cmb-config/:/cmb-config/

    command: >
      --config /cmb-config/messenger-config.yaml

  partner-plugin:
    build:
      context: .
      dockerfile: Dockerfile.partner-plugin

    image: camino-refundio-partner-plugin

    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend

    image: camino-campensation-backend

    ports:
      - "3000:3000"

    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend

    image: camino-campensation-frontend

    ports:
      - "8080:80"

    env_file:
      - .env