# build stage
FROM node:lts-alpine AS build-stage

WORKDIR /frontend

COPY ./distributor/frontend .

RUN npm install
RUN npm run build

# runtime stage
FROM nginx:alpine AS runtime-stage

COPY --from=build-stage /frontend/dist /usr/share/nginx/html
COPY ./distributor/frontend/nginx/nginx.conf /etc/nginx/nginx.conf

