services:
  distributor-bot:
    image: c4tplatform/camino-messenger-bot

    volumes:
      - ./distributor/cmb-config/:/cmb-config/

    command: |
      --config /cmb-config/messenger-config.yaml

    ports:
      - "9090:9090"

  supplier-bot:
    image: c4tplatform/camino-messenger-bot

    volumes:
      - ./supplier/cmb-config/:/cmb-config/

    command: >
      --config /cmb-config/messenger-config.yaml

  partner-plugin:
    build:
      context: .
      dockerfile: Dockerfile.partner-plugin
      
    image: camino-refundio-partner-plugin